### ISSUE TITLE
Wrong display of frostbolt icon as Cone of Cold Icon

### ISSUE THREAD

**Issue by supremecwj** [wardz/ClassicCastbars#16] opened 2019-09-24 02:30 UTC
Hi,thx for your addons
I found a bug
Version starting after 1.0.0
Wrong display of frostbolt icon as Cone of Cold Icon

**Comment by wardz** [comment] 2019-09-24 11:02
Where did you encounter this?

**Comment by supremecwj** [comment] 2019-09-25 03:31
cn servers. target cast frostbolt,but icon display cone of cold.

**Comment by wardz** [comment] 2019-09-25 12:16
Hmm weird, it works fine on the English client. Unfortunately I don't have access to chinese client so I cant test it there, but I tried changing the spell data from Frostbolt rank 9 to rank 10 as your game might have cached the wrong spell for some reason. I will upload the change soon in a few hours.

**Comment by supremecwj** [comment] 2019-09-25 16:22
thank you very much. however ,the version before 1.0.0 works well .1.02 ~1.07 do not work correctly. 


------------------ 原始邮件 ------------------
发件人: "Thomas"<notifications@github.com>;
发送时间: 2019年9月25日(星期三) 晚上8:16
收件人: "wardz/ClassicCastbars"<ClassicCastbars@noreply.github.com>;
抄送: "Supreme"<188980229@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wardz/ClassicCastbars] Wrong display of frostbolt icon as Coneof Cold Icon (#16)




Hmm weird, it works fine on the English client. Unfortunately I don't have access to chinese client so I cant test it there, but I tried changing the spell data from Frostbolt rank 9 to rank 10 as your game might have cached the wrong spell for some reason. I will upload the change soon in a few hours.

**Comment by supremecwj** [comment] 2019-09-25 17:14
the 1.08 version  still can not show frostbolt icon correctly on chinese client. thank you for your work sincerely. 





------------------ 原始邮件 ------------------
发件人: "Thomas"<notifications@github.com>;
发送时间: 2019年9月25日(星期三) 晚上8:16
收件人: "wardz/ClassicCastbars"<ClassicCastbars@noreply.github.com>;
抄送: "Supreme"<188980229@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wardz/ClassicCastbars] Wrong display of frostbolt icon as Coneof Cold Icon (#16)




Hmm weird, it works fine on the English client. Unfortunately I don't have access to chinese client so I cant test it there, but I tried changing the spell data from Frostbolt rank 9 to rank 10 as your game might have cached the wrong spell for some reason. I will upload the change soon in a few hours.

**Comment by wardz** [comment] 2019-09-25 17:30
It must be something wrong with the Chinese client then as v1.0.0-next.6 to v1.0.8 all use the same spell data. You can try deleting your cache folder in ```C:\Program Files (x86)\World of Warcraft Public Test\_retail_\Cache```. If that does not fix it you should report this to Blizzard.

**Comment by supremecwj** [comment] 2019-09-25 18:47
I try delet cache,wtf,interface. its still not working.
I replace 1.0.6data with 1.0.0data,and use v1.0.6.  target cast frostbolt, icon is correctly.but castbar will briefly display and disappear immediately.other spells work correctly.
if replace 1.0.7&1.0.8data with 1.0.0data, castbar can't display the frostbolt spell,but other spells work correctly.
I will report this to Blizzard.
Thank you very much.




------------------ 原始邮件 ------------------
发件人: "Thomas"<notifications@github.com>;
发送时间: 2019年9月26日(星期四) 凌晨1:30
收件人: "wardz/ClassicCastbars"<ClassicCastbars@noreply.github.com>;
抄送: "Supreme"<188980229@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wardz/ClassicCastbars] Wrong display of frostbolt icon as Coneof Cold Icon (#16)




It must be something wrong with the Chinese client then as v1.0.0-next.6 to v1.0.8 all use the same spell data. You can try deleting your cache folder in C:\Program Files (x86)\World of Warcraft Public Test\_retail_\Cache. If that does not fix it you should report this to Blizzard.

**Comment by supremecwj** [comment] 2019-09-25 19:46
HI, I asked my friend to modify it, and the Chinese client works fine.


------------------ 原始邮件 ------------------
发件人: "Thomas"<notifications@github.com>;
发送时间: 2019年9月26日(星期四) 凌晨1:30
收件人: "wardz/ClassicCastbars"<ClassicCastbars@noreply.github.com>;
抄送: "Supreme"<188980229@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wardz/ClassicCastbars] Wrong display of frostbolt icon as Coneof Cold Icon (#16)




It must be something wrong with the Chinese client then as v1.0.0-next.6 to v1.0.8 all use the same spell data. You can try deleting your cache folder in C:\Program Files (x86)\World of Warcraft Public Test\_retail_\Cache. If that does not fix it you should report this to Blizzard.

**Comment by wardz** [comment] 2019-09-25 20:40
Awesome! Mind sharing the fix? I could add it in so other cn users gets it working aswell

**Comment by supremecwj** [comment] 2019-09-26 03:20
I don't mind.The attachment was sent to you.




------------------ 原始邮件 ------------------
发件人: "Thomas"<notifications@github.com>;
发送时间: 2019年9月26日(星期四) 凌晨4:40
收件人: "wardz/ClassicCastbars"<ClassicCastbars@noreply.github.com>;
抄送: "Supreme"<188980229@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wardz/ClassicCastbars] Wrong display of frostbolt icon as Coneof Cold Icon (#16)




Awesome! Mind sharing the fix? I could add it in so other cn users gets it working aswell

**Comment by wardz** [comment] 2019-09-26 06:57
I don't think it worked because the attachment was sent through Github email, try sending it to me on `thomaszrx@gmail.com` instead. Thanks

**Comment by wardz** [comment] 2019-09-26 10:46
Got it now, thanks :)

Will try to fix it soon in next version.

**Comment by wardz** [comment] 2019-10-02 19:02
Hi again, could you test if this is fixed in v1.0.9? 

I think the issue is that there's another NPC spell with the exact same name as Frostbolt in the chinese client, but not the English client, so the addon picks the last one from the list. I'm not completely sure though.

**Comment by supremecwj** [comment] 2019-10-03 00:48
HI~
v1.0.9 works fine in Chinese client. thank you for your work sincerely.
: )





------------------ 原始邮件 ------------------
发件人: "Thomas"<notifications@github.com>;
发送时间: 2019年10月3日(星期四) 凌晨3:02
收件人: "wardz/ClassicCastbars"<ClassicCastbars@noreply.github.com>;
抄送: "Supreme"<188980229@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wardz/ClassicCastbars] Wrong display of frostbolt icon as Coneof Cold Icon (#16)




Hi again, could you test if this is fixed in v1.0.9?
 
I think the issue is that there's another NPC spell with the exact same name as Frostbolt in the chinese client, but not the English client, so the addon picks the last one from the list. I'm not completely sure though.

**Closed** 2019-10-03 08:17 UTC
Labels: bug
